# Generated by Django 5.2.13 on 2026-05-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_countryeventsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UNResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcid', models.IntegerField(db_index=True, unique=True)),
                ('session', models.IntegerField(blank=True, null=True)),
                ('vote_date', models.DateField(db_index=True)),
                ('title', models.TextField(blank=True)),
                ('body', models.CharField(choices=[('UNGA', 'UN General Assembly'), ('UNSC', 'UN Security Council')], default='UNGA', max_length=10)),
                ('short_description', models.TextField(blank=True)),
                ('topic_tags', models.JSONField(default=list)),
                ('un_symbol', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-vote_date'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='blocs',
            field=models.ManyToManyField(blank=True, related_name='countries', to='core.countrybloc'),
        ),
        migrations.CreateModel(
            name='UNVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain'), ('absent', 'Absent'), ('not_member', 'Not a Member')], max_length=15)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_votes', to='core.country')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.unresolution')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'vote'], name='core_unvote_country_dc317f_idx')],
                'unique_together': {('resolution', 'country')},
            },
        ),
    ]
