# Generated by Django 5.2.13 on 2026-05-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_countrybloc_unresolution_unvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpost',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter/X'), ('web', 'Web Scrape'), ('pdf', 'PDF Document'), ('javascript', 'JS Page'), ('gdelt', 'GDELT News'), ('rss', 'RSS Feed'), ('scrape', 'Gov Archive Scrape')], max_length=50),
        ),
        migrations.AlterField(
            model_name='statement',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('event', 'country', 'source_url'), name='unique_statement_per_source_url'),
        ),
    ]
