# Generated by Django 5.2.13 on 2026-05-24 15:46

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rawpost_platform_choices_statement_dedup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_name', models.CharField(max_length=255)),
                ('suggested_description', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('article_count', models.IntegerField(default=1)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved — Event Created'), ('merged', 'Merged with Existing Event'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-article_count', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='event_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddField(
            model_name='eventsuggestion',
            name='approved_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_suggestions', to='core.event'),
        ),
        migrations.AddField(
            model_name='eventsuggestion',
            name='nearest_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='near_suggestions', to='core.event'),
        ),
        migrations.AddField(
            model_name='eventsuggestion',
            name='supporting_posts',
            field=models.ManyToManyField(blank=True, related_name='event_suggestions', to='core.rawpost'),
        ),
        migrations.AddIndex(
            model_name='eventsuggestion',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='eventsugg_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
