# Generated by Django 5.2.13 on 2026-05-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_event_embedding_event_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='unresolution',
            name='ai_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='unresolution',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unresolution',
            name='explanation_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unresolution',
            name='symbol_tags',
            field=models.JSONField(default=list),
        ),
    ]
