# Generated by Django 5.2.13 on 2026-05-25 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_unresolution_three_layer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='unresolution',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='un_resolutions', to='core.event'),
        ),
        migrations.AddField(
            model_name='unresolution',
            name='event_classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unresolution',
            name='resolution_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unresolution',
            name='undl_id',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='unresolution',
            name='body',
            field=models.CharField(choices=[('UNGA', 'UN General Assembly'), ('UNSC', 'UN Security Council'), ('UNHRC', 'UN Human Rights Council')], default='UNGA', max_length=10),
        ),
        migrations.AlterField(
            model_name='unresolution',
            name='rcid',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='unresolution',
            name='un_symbol',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='unresolution',
            constraint=models.UniqueConstraint(condition=models.Q(('un_symbol', ''), _negated=True), fields=('un_symbol',), name='unique_unresolution_un_symbol'),
        ),
    ]
