# Generated by Django 5.2.13 on 2026-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_unresolution_undl_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='unresolution',
            name='meeting_record_symbol',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='unresolution',
            name='press_release_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='unvote',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
